name: Paivita KITI Data

on:
  schedule:
    - cron: '0 2 * * *' # Ajaa automaattisesti joka yö klo 02:00
  workflow_dispatch: # Mahdollistaa ajon napista milloin vain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Asenna Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Asenna paketit
        run: pip install requests

      - name: Hae KITI tulokset
        run: python scraper.py

      - name: Tallenna muutokset GitHubiin
        run: |
          git config --global user.name 'KhjA Bot'
          git config --global user.email 'bot@khja.fi'
          git add data.json
          git commit -m "Automaattinen KITI-data päivitys" || exit 0
          git push
